CREATE TABLE COMPROVANTE_DE_ALUGUEL (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        AGENCIA VARCHAR(255) NOT NULL,
        CLIENTE VARCHAR(255) NOT NULL,
        VEICULO VARCHAR(255) NOT NULL,
        DATA_HORA_ALUGUEL TIMESTAMP NOT NULL,
        DATA_HORA_DEVOLUCAO TIMESTAMP NOT NULL,
        VALOR_DA_LOCACAO DECIMAL(10, 2) NOT NULL,
        CONSTRAINT fk_agencia FOREIGN KEY (AGENCIA) REFERENCES AGENCIA(id),
        CONSTRAINT fk_cliente FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(id),
        CONSTRAINT fk_veiculo FOREIGN KEY (VEICULO) REFERENCES VEICULO(id)
);
