CREATE TABLE AGENCIA (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    TAMANHO_MAXIMO_DA_FROTA INT NOT NULL,
    ENDERECO_ID VARCHAR(10),
    CONSTRAINT FK_AGENCIA_ENDERECO FOREIGN KEY (ENDERECO_ID)
        REFERENCES ENDERECO(CEP)
        ON DELETE SET NULL
        ON UPDATE CASCADE
);