INSERT INTO AGENCIA (TAMANHO_MAXIMO_DA_FROTA, ENDERECO_ID)
VALUES (43, (SELECT CEP FROM ENDERECO WHERE CEP = '79010913'));

INSERT INTO AGENCIA (TAMANHO_MAXIMO_DA_FROTA, ENDERECO_ID)
VALUES (11, (SELECT CEP FROM ENDERECO WHERE CEP = '59025560'));

INSERT INTO AGENCIA (TAMANHO_MAXIMO_DA_FROTA, ENDERECO_ID)
VALUES (16, (SELECT CEP FROM ENDERECO WHERE CEP = '59160772'));

INSERT INTO AGENCIA (TAMANHO_MAXIMO_DA_FROTA, ENDERECO_ID)
VALUES (19, (SELECT CEP FROM ENDERECO WHERE CEP = '76825452'));

INSERT INTO AGENCIA (TAMANHO_MAXIMO_DA_FROTA, ENDERECO_ID)
VALUES (11, (SELECT CEP FROM ENDERECO WHERE CEP = '69104042'));

INSERT INTO AGENCIA (TAMANHO_MAXIMO_DA_FROTA, ENDERECO_ID)
VALUES (13, (SELECT CEP FROM ENDERECO WHERE CEP = '85857160'));

INSERT INTO AGENCIA (TAMANHO_MAXIMO_DA_FROTA, ENDERECO_ID)
VALUES (48, (SELECT CEP FROM ENDERECO WHERE CEP = '76913650'));

INSERT INTO AGENCIA (TAMANHO_MAXIMO_DA_FROTA, ENDERECO_ID)
VALUES (27, (SELECT CEP FROM ENDERECO WHERE CEP = '76906754'));

INSERT INTO AGENCIA (TAMANHO_MAXIMO_DA_FROTA, ENDERECO_ID)
VALUES (41, (SELECT CEP FROM ENDERECO WHERE CEP = '24417480'));

INSERT INTO AGENCIA (TAMANHO_MAXIMO_DA_FROTA, ENDERECO_ID)
VALUES (13, (SELECT CEP FROM ENDERECO WHERE CEP = '96503656'));
