CREATE TABLE VEICULO (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    MODELO VARCHAR(255) NOT NULL,
    PLACA VARCHAR(50) NOT NULL,
    ANO INT NOT NULL,
    COR VARCHAR(50),
    TIPO_VEICULO VARCHAR(50),
    VEICULO_DISPONIVEL_PARA_LOCACAO BOOLEAN NOT NULL,
    AGENCIA_ID BIGINT,
    CONSTRAINT FK_VEICULO_AGENCIA FOREIGN KEY (AGENCIA_ID)
        REFERENCES AGENCIA(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);